# Generated by Django 4.1.6 on 2023-03-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=100,
                                          verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),  # noqa: E501
            ],
        ),
    ]
